project:
  type: book
  output-dir: docs

book:
  title: "Museum Guidebooks"
  author: 
    name: "Team Data Science, HsH"
    affiliations: 
        - "Hanover University of Applied Sciences and Arts"
        - "Open Science Lab, TIB"
        - "NFDI4Culture"
  date: today
  favicon: ./images/favicon-32x32.png
  chapters:
    - index.qmd
    - guide001.ipynb
    - guide002.ipynb
    - guide003.ipynb
    - about.qmd
    - cs.qmd
  cover-image: WikiMap-04-04-2025_05_12_PM.jpg
  repo-url: https://github.com/NFDI4Culture/open-museum
  repo-actions: [issue]  
  downloads: [pdf,docx]  
  sidebar: 
   logo: WikiMap-04-04-2025_05_12_PM.jpg
  bread-crumbs: true

format:
  html:
    toc: false
    number-sections: true
    theme: brite
  pdf:
    documentclass: book
  docx: 
    number-sections: false
    toc: true



